### ISSUE TITLE
Investigate Fabrikate config

### ISSUE THREAD

**Issue by edaena** [andrewDoing/hydrate#12]
As a developer I want to understand the options of a fabrikate component to be able to determine what can be auto-generated.

**Comment by andrewDoing** [comment]
## Investigation Results
Going from the cluster to a high level deployment definition is challenging for a few reasons.

1. The cluster contains components, there's no sub-component hierarchy, except within deployments.

2. The cluster doesn't have all the information needed to generate an HLD

3. There are never direct source links to Github for a given component.

So if the cluster only provides a certain level of information, we need to acquire the rest from another source. The information required to create an HLD of a given cluster can be obtained from three sources.

### Source 1: The Cluster
Using the kubernetes API, we can determine the following:

- Component Name

- Component Namespace

- How it was generated (helm for example)

- Image Version

- Chart Version

### Source 2: Github
Using the information we gather from the cluster, along with Github's API and some clever programming, we can determine the following:

- Source (Github Repository or local path)

- Path (Relative path to this component from the root of the source)

- Branch (Which branch needs to be checked out after cloning)

- Repositories (Key-Value pairs of a set of helm repos (used for incubator charts))

### Source 3: User Config
There are aspects of an HLD that must be given by the user. The user will also want to override any information incorrectly obtained from Github.

- Method (Default: git)

- Hooks (shell commands surrounding the component's life cycle)

- Component configuration
