### ISSUE TITLE
Suggest Fabrikate Components

### ISSUE THREAD

**Issue by edaena** [andrewDoing/hydrate#13]
As a user I want to get suggestions of existing fabrikate components that I can use.

Additional context:
-Determine what fabrikate components can be pre-populated.
- [x] Identify a fabrikate component in the cluster
- [x] Find existing Fabrikate Components on GitHub.
- [ ] Allow the User to choose a best match repository, version, and branch.
- [x] Apply the best match information to the component.yaml

Scenarios:
- [x] Full match: The deployments on the cluster fully match an existing Fabrikate Component.
  - Full matches can be automatically added to the HLD without User intervention.
- Partial match: There are deployments on the cluster that are contained within an existing Fabrikate Component, but the existing Component contains other deployments not present on the cluster.
  - Partial matches need User input. Users can choose to use the Component, adding the missing deployments. Or they can opt not to.
- No match: There are deployments on the cluster that have no corresponding Fabrikate component.
  - No matches need the User to turn their deployment into a Fabrikate Component.

Move Partial Match and No match scenarios to new Post-MVP issue #29
Move Selection of specific versions/branches to new Post-MVP issue #30

**Comment by andrewDoing** [comment]
Link to wiki page that contains existing Fabrikate components: https://github.com/Microsoft/fabrikate/wiki/Component-List

We could use the GitHub API to compile a list of repositories that start with "Fabrikate-" to automate this list.

So from these two sources we ought to be able to match existing components on a given cluster to the matching Fabrikate components that exist on GitHub.

**Comment by andrewDoing** [comment]
Another factor in determining the components is removing the false positives. This includes pods/deployments that fall under the kube-system namespace. These are part of any kubernetes cluster, and don't need to be considered when creating an HLD.
