### ISSUE TITLE
Demo Environment (Setup)

### ISSUE THREAD

**Issue by edaena** [andrewDoing/hydrate#19]
As a developer I want to have a demo environment that is stable to demo the progress.

- [x] Setup a cluster

- [ ] Determine what applications to deploy to the cluster

**Comment by andrewDoing** [comment]
The demo environment should contain multiple clusters that span the user scenarios of the hydrate tool.

- [x] Cluster Deployments in their own namespaces.

-  The demo-cluster contains the Fabrikate cloud-native stack.

- [ ] Cluster Deployments all in default namespace.

- [ ] Cluster Environments in their own namespaces. (Multiple deployments per namespace).
