### ISSUE TITLE
Generate component.yaml template

### ISSUE THREAD

**Issue by edaena** [andrewDoing/hydrate#2]
As a user I want an auto-generated fabrikate component.yaml of what is deployed in a Kubernetes cluster so that I don't have to manually generate it.

References:
[Fabrikate Component Object Definition](https://github.com/microsoft/fabrikate/blob/master/docs/component.md)
[Fabrikate Config Definition](https://github.com/microsoft/fabrikate/blob/master/docs/config.md)

Describe the solution:

- [ ] Parse the output from the cluster
- [ ] Generate a fabrikate component.yaml with the information from the cluster
- [ ] Accept User Input for missing fields.

**Comment by andrewDoing** [comment]
For the future, it'd be cool if Hydrate automatically updated to match the component.yaml template created by Fabrikate. For now, the simplest thing to do will be to program the template as it is now and watch for changes.

As far as automatic updates, I'm not sure the best way to accomplish this. Some ideas:

- Pull the information from the Fabrikate Repo (the wiki, a code file, etc.)
