### ISSUE TITLE
Hydrate run command fails

### ISSUE THREAD

**Issue by andrebriggs** [andrewDoing/hydrate#23]
After cloning the repo I attempt the following from the [instructions](https://github.com/andrewDoing/hydrate#basic-usage):

`$ python hydrate.py run`

The shell result is
`
  File "hydrate.py", line 48
    verbose_print = print if args.verbose else lambda *a, **k: None
                        ^
SyntaxError: invalid syntax
`

**Comment by andrewDoing** [comment]
I believe the issue is python 2 vs 3, this requirement is reflected in the updated README.
