### ISSUE TITLE
Define User Experience

### ISSUE THREAD

**Issue by edaena** [andrewDoing/hydrate#4]
As a user I want to set values and options via commands and flags so that I can customize what hydrate will generate.

**Additional context:**
-How will customers use this tool? 
-Think about user experience 
-What arguments should it take in? 
-What flags are optional? 
-What is the output? 

We can suggest something like  
```
$ mkdir my-cluster-hld 
$ hydrate run --output ./my-cluster-hld //Writes component.yaml to my-cluster-hld dir 
```
Or  
`$ hydrate run --dry-run  //print out the component.yaml it would generate `

The above suggests dry run feature. What are the bare minimum actions we need from the command line tool?

**Comment by andrewDoing** [comment]
### How will customers use this tool?

A Command Line Interface

### The User Experience

The User is assumed to be a developer seeking to create an HLD of their kubernetes cluster to use Bedrock.
Using the command line interface should be:

- Executable with few commands

- Have sufficient documentation

- Include useful optional arguments for debugging/extension

Hydrate shall handle the following user scenarios:

- Each application has its own namespace 

- All applications are in the default namespace 

- Multiple environments on one cluster segmented by namespace

### What arguments should it take in?

- run: Executes the hydrate code on the default configured cluster

- --output, -o: The location where the component.yaml file shall be written (default: current directory)

### What flags are optional?

- --name, -n: Specify the name of the component

- --verbose, -v: More information printed to the terminal. 

- --dry-run, -d: Print the component.yaml text to the terminal.

- --help, -h: Print the help documentation

### What is the output?

- The component.yaml file

### What are the bare minimum actions we need from the command line tool?

- Collect information from the user

- Collect information from a kubernetes cluster

- Use both sets of information to generate the component.yaml file

**Comment by edaena** [comment]
@andrewDoing This looks good. One more option can be to take the name of the main component via a flag.
For example the name of [this component](https://github.com/microsoft/fabrikate-production-cluster-demo/blob/master/component.yaml) is `production-demo`.

**Comment by andrewDoing** [comment]
@edaena Good idea, updated the response.
